FIX: no race condition waiting for the pod to start

diff --git a/src/pvc-rsync/clone-tools/convert-pvc-sc b/src/pvc-rsync/clone-tools/convert-pvc-sc
--- a/src/pvc-rsync/clone-tools/convert-pvc-sc
+++ b/src/pvc-rsync/clone-tools/convert-pvc-sc
@@ -171,16 +171,37 @@ is_pod_terminated()
 wait_until_pod_is_running()
 {
 	local POD="${1}"
+	local NEXT_WAIT=${POD_POLL_WAIT}
+	local FIRST="true"
+	local START="$(/usr/bin/date +%s)"
+	local END="$(( START + POD_REBOOT_TIMEOUT ))"
+	while true; do
+		if ! "${FIRST}" ; then
+			# Edge case ... 
+			is_pod_terminated "${POD}" && return 0
 
-	local OUT=""
-	OUT="$("${KUBECTL}" wait pod \
-		--namespace "${NAMESPACE}" "${POD}" \
-		--for condition=Ready \
-		--timeout="${POD_REBOOT_TIMEOUT}s" 2>&1)" && return 0
+			# Apply the polling wait ...
+			say "💤 Sleeping for ${NEXT_WAIT} before checking for status again..."
+			/usr/bin/sleep ${NEXT_WAIT} || return ${?}
+		fi
 
-	local RC=${?}
-	err "The pod reboot timeout has expired, please check the pod for issues (rc=${RC})\n${OUT}"
-	return ${RC}
+		local OUT=""
+		OUT="$("${KUBECTL}" wait pod \
+			--namespace "${NAMESPACE}" "${POD}" \
+			--for condition=Ready \
+			--timeout="${NEXT_WAIT}s" 2>&1)" && return 0
+
+		"${FIRST}" && warn "The pod ${NAMESPACE}/${POD} isn't running yet..."
+		FIRST="false"
+
+		local NOW="$(/usr/bin/date +%s)"
+		[ $(( NOW - START )) -ge ${POD_REBOOT_TIMEOUT} ] && break
+		[ $(( NOW + NEXT_WAIT )) -lt ${END} ] || NEXT_WAIT=$(( END - NOW ))
+	done
+
+	# Should never happen, but if it does...
+	err "The pod didn't start running in ${POD_REBOOT_TIMEOUT} seconds, can't wait anymore"
+	return 1
 }
 
 wait_until_pod_terminates()
@@ -201,7 +222,7 @@ wait_until_pod_terminates()
 track_logs()
 {
 	local POD="${1}"
-	say "👀 Tacking the logs for ${NAMESPACE}/${POD}"
+	say "👀 Tracking the logs for ${NAMESPACE}/${POD}"
 	"${KUBECTL}" logs \
 		--namespace "${NAMESPACE}" \
 		--tail=1000 \
@@ -232,6 +253,7 @@ get_copy_result()
 		wait_until_pod_exists "${POD}" || fail "The pod did not come online"
 
 		if ! is_pod_terminated "${POD}" ; then
+
 			# Step 2: wait until the pod is running
 			ok "The pod ${NAMESPACE}/${POD} exists! Waiting for it to be Ready"
 			wait_until_pod_is_running "${POD}" || fail "The pod never reached the running state"
