Fixed the copy process, removed per-PVC logs

diff --git a/copy-pvcs-to-pod b/copy-pvcs-to-pod
--- a/copy-pvcs-to-pod
+++ b/copy-pvcs-to-pod
@@ -85,19 +85,11 @@ exec 2>&1
 say "👉 Copying from [${BASE_DIR}] into the pod ${NSMSG}${TARGET_POD}"
 while read pvc src ; do
 	STAMP="$(/usr/bin/date -u +%Y%m%d-%H%M%SZ)"
-	PVC_LOG="${LOG_BASE}.${pvc}.${STAMP}.log"
+	say "👉 Copying files from [${src}] into [${NSMSG}${pvc}]..."
 	(
 		set -euo pipefail
-		exec > >("${TEE}" "${PVC_LOG}")
-		exec 2>&1
-
-		say "👉 Copying files from [${src}] into [${NSMSG}${pvc}]..."
-		# The first tar command isn't substituted b/c it's a remote command
-		( cd "${src}" && "${TAR}" -czf - . ) | "${KUBECTL}" exec "${NSFLAG[@]}" -i "${TARGET_POD}" -- tar -C "/pvc/${pvc}" -xzvf -
-		for RC in "${PIPESTATUS[@]}" ; do
-			[ ${RC} -eq 0 ] || fail "Failed to copy the data (rc = [${PIPESTATUS[@]}])"
-		done
-		ok "File copy complete!"
-		exit 0
-	) || exit ${?}
+		cd "${src}"
+		exec "${KUBECTL}" cp --retries=999 . "${TARGET_POD}:/pvc/${pvc}"
+	) || fail "Failed to copy the data (rc = ${?})"
+	ok "File copy complete!"
 done < <(path_to_pvc "${BASE_DIR}" | "${SORT}")
