Some important bugfixes

diff --git a/src/pvc-rsync/scripts/rsync-pvcs b/src/pvc-rsync/scripts/rsync-pvcs
--- a/src/pvc-rsync/scripts/rsync-pvcs
+++ b/src/pvc-rsync/scripts/rsync-pvcs
@@ -32,40 +32,51 @@ fail()
 
 usage()
 {
-	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [base-dir] [user@]rsyncd-server"
+	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} pod[@namespace]"
+	echo -e ""
+	echo -e "	Copy the PVC data, as read from STDIN in a two-column format"
+	echo -e "	where the first column is the PVC name, and the rest of the line"
+	echo -e "	is the directory path where the data for that PVC is stored."
+	echo -e ""
+	echo -e "	The RSYNC session will be opened using kubectl exec, so not the"
+	echo -e "	most efficient, but can help avoid some networking limitations."
 	exit 1
 }
 
-find_pvcs()
-{
-	local ROOT_DIR="${1}"
-	while read DIR ; do
-		echo "$(basename "${DIR}")" "${DIR}"
-	done < <("${FIND}" "${ROOT_DIR}" -mindepth 1 -maxdepth 1 -type d | "${SORT}")
-}
+[ ${#} -eq 1 ] || usage
 
-if [ ${#} -eq 1 ] ; then
-	ROOT_DIR="."
-	RSYNCD_SERVER="${1}"
-elif [ ${#} -eq 2 ] ; then
-	ROOT_DIR="${1}"
-	[ -e "${ROOT_DIR}" ] || fail "The directory [${ROOT_DIR}] does not exist"
-	[ -d "${ROOT_DIR}" ] || fail "The path [${ROOT_DIR}] is not a directory"
-	[ -r "${ROOT_DIR}" ] || fail "The directory [${ROOT_DIR}] is not readable"
-	[ -x "${ROOT_DIR}" ] || fail "The directory [${ROOT_DIR}] is not executable"
-	RSYNCD_SERVER="${2}"
-else
-	usage
-fi
+RSYNCD_SERVER="${1}"
 
-ROOT_DIR="$(readlink -f "${ROOT_DIR}")"
-[[ "${RSYNCD_SERVER,,}" =~ ^([a-z0-9_-]+@)?[a-z0-9]([a-z0-9-]*[a-z0-9])?([.][a-z0-9]([a-z0-9-]*[a-z0-9])?)*$ ]] || fail "The rsyncd-server value is invalid: [${RSYNCD_SERVER}]"
+case "${RSYNCD_SERVER}" in
+	rsync://* )
+		PROTOCOL="rsync"
+		RSYNCD_SERVER="$(parse_rsync_url "${RSYNCD_SERVER}")"
+		[[ "${RSYNCD_SERVER,,}" =~ ^rsync://((.+@)?[a-z0-9]([a-z0-9-]*[a-z0-9])?([.][a-z0-9]([a-z0-9-]*[a-z0-9])?)*)$ ]] || fail "The rsyncd-server value is invalid: [${RSYNCD_SERVER}]"
+		RSYNCD_SERVER="${BASH_REMATCH[2]}"
+		;;
 
+	kubectl://* )
+		PROTOCOL="kubectl"
+		RSYNCD_SERVER="$(parse_kubectl_url "${RSYNCD_SERVER}")"
+		[[ "${RSYNCD_SERVER,,}" =~ ^kubectl://([a-z0-9]([a-z0-9-]*[a-z0-9])?(@([a-z0-9]([a-z0-9-]*[a-z0-9])?)))$ ]] || fail "The rsyncd-server value is invalid: [${RSYNCD_SERVER}]"
+		RSYNCD_SERVER="${BASH_REMATCH[2]}"
+		RSYNC_SHELL="${BASEDIR}/kubectl-helper"
+		[ -e "${RSYNC_SHELL}" ] || fail "The $(basename "${RSYNC_SHELL}") could not be found at [${RSYNC_SHELL}]"
+		[ -f "${RSYNC_SHELL}" ] || fail "The path [${RSYNC_SHELL}] is not a regular file"
+		[ -r "${RSYNC_SHELL}" ] || fail "The file [${RSYNC_SHELL}] is not readable"
+		[ -x "${RSYNC_SHELL}" ] || fail "The file [${RSYNC_SHELL}] is not executable"
+		export RSYNC_SHELL
+		;;
+
+	* ) fail "Unrecognized RSYNCD server, must be an rsync://... or kubectl://... URL" ;;
+esac
+
+KUBECTL="$(type -P kubectl)" || fail "Failed to find kubectl in the path"
+SED="$(type -P sed)" || fail "Failed to find sed in the path"
 TEE="$(type -P tee)" || fail "Failed to find tee in the path"
+TAR="$(type -P tar)" || fail "Failed to find tar in the path"
 SORT="$(type -P sort)" || fail "Failed to find sort in the path"
 RSYNC="$(type -P rsync)" || fail "Failed to find rsync in the path"
-FIND="$(type -P find)" || fail "Failed to find find in the path"
-BASENAME="$(type -P basename)" || fail "Failed to find basename in the path"
 
 RSYNC_WITH_RETRY="${BASEDIR}/rsync-with-retry"
 [ -e "${RSYNC_WITH_RETRY}" ] || fail "The $(basename "${RSYNC_WITH_RETRY}") script could not be found at [${RSYNC_WITH_RETRY}]"
@@ -73,13 +84,13 @@ RSYNC_WITH_RETRY="${BASEDIR}/rsync-with-retry"
 [ -r "${RSYNC_WITH_RETRY}" ] || fail "The file [${RSYNC_WITH_RETRY}] is not readable"
 [ -x "${RSYNC_WITH_RETRY}" ] || fail "The file [${RSYNC_WITH_RETRY}] is not executable"
 
-LOG_BASE="$("${BASENAME}" "${0}")"
+LOG_BASE="$(basename "${0}")"
 STAMP="$(/usr/bin/date -u "+%Y%m%d-%H%M%SZ")"
 MAIN_LOG="${LOG_BASE}.${STAMP}.log"
 
 exec > >("${TEE}" "${MAIN_LOG}")
 exec 2>&1
-say "👉 Copying all the PVCs from [${ROOT_DIR}] into the rsyncd at ${RSYNCD_SERVER}"
+say "👉 Copying all the PVCs into the server ${RSYNCD_SERVER} via ${PROTOCOL}"
 while read PVC_NAME PVC_DIR ; do
 	STAMP="$(/usr/bin/date -u "+%Y%m%d-%H%M%SZ")"
 	PVC_LOG="${LOG_BASE}.${PVC_NAME}.${STAMP}.log"
@@ -87,4 +98,4 @@ while read PVC_NAME PVC_DIR ; do
 	say "👉 Processing ${PVC_NAME} from [${PVC_DIR}]..."
 	"${RSYNC_WITH_RETRY}" "${PVC_DIR}" "${RSYNCD_SERVER}::${PVC_NAME}" &> "${PVC_LOG}" || fail "Processing failed (rc = ${?})"
 	ok "Directory processed!"
-done < <(find_pvcs "${ROOT_DIR}")
+done
