Fix Solr race conditions on initialization

diff --git a/src/app/charts/search/files/configmap/txt/entrypoint b/src/app/charts/search/files/configmap/txt/entrypoint
--- a/src/app/charts/search/files/configmap/txt/entrypoint
+++ b/src/app/charts/search/files/configmap/txt/entrypoint
@@ -22,27 +22,6 @@ set -euo pipefail
 
 acme-init
 
-#
-# Now, continue with the boot
-#
-
-[ -v INIT_MARKER ] || INIT_MARKER="${DATA_DIR}/.initialized"
-
-# This is important: ${HOME_DIR} must be *ephemeral* - this flag is only meant to
-# inform when the init script ran, so we can run the post-init script in the helm chart
-[ -v RUN_MARKER ] || RUN_MARKER="${HOME_DIR}/.initRan"
-
-if [ -e "${INIT_MARKER}" ] ; then
-	say "Persistence is already initialized, proceeding with the normal boot"
-else
-	say "Persistence has not been initialized, proceeding with the first-time initialization"
-
-	/config-pre.sh || fail "Pre-configuration failed - the Solr initialization may not be complete"
-
-	touch "${INIT_MARKER}"
-	touch "${RUN_MARKER}"
-fi
-
 [ -v SOLR_LOGS_DIR ] || export SOLR_LOGS_DIR="${DATA_DIR}/logs"
 [ -d "${SOLR_LOGS_DIR}" ] || mkdir -p "${SOLR_LOGS_DIR}" || say "WARNING: Failed to find and create the log directory at [${SOLR_LOGS_DIR}]"
 
@@ -78,6 +57,27 @@ if [ -v ZK_HOST ] ; then
 		exec server/scripts/cloud-scripts/zkcli.sh -zkhost "${ZK_HOST}" -cmd clusterprop -name urlScheme -val https
 	)
 	say "SSL Enabled!"
+fi
+
+#
+# Now, continue with the boot
+#
+
+[ -v INIT_MARKER ] || INIT_MARKER="${DATA_DIR}/.initialized"
+
+# This is important: ${HOME_DIR} must be *ephemeral* - this flag is only meant to
+# inform when the init script ran, so we can run the post-init script in the helm chart
+[ -v RUN_MARKER ] || RUN_MARKER="${HOME_DIR}/.initRan"
+
+if [ -e "${INIT_MARKER}" ] ; then
+	say "Persistence is already initialized, proceeding with the normal boot"
+else
+	say "Persistence has not been initialized, proceeding with the first-time initialization"
+
+	/config-pre.sh || fail "Pre-configuration failed - the Solr initialization may not be complete"
+
+	touch "${INIT_MARKER}"
+	touch "${RUN_MARKER}"
 fi
 
 set -- "${HOME_DIR}/bin/solr" start -f -cloud
