Updated common and added initDeps for clustering

diff --git a/src/solr/files/configmap/txt/entrypoint b/src/solr/files/configmap/txt/entrypoint
--- a/src/solr/files/configmap/txt/entrypoint
+++ b/src/solr/files/configmap/txt/entrypoint
@@ -60,6 +60,21 @@ if [ -v ZK_HOST ] ; then
 	export ZK_HOST="$(echo -n "${ZK[@]}" | tr ' ' ',')"
 fi
 
+MAX_BOOT_DELAY="60"
+if [ -v BOOT_DELAY ] && [[ "${BOOT_DELAY}" =~ ^[0-9]+$ ]] ; then
+	BOOT_DELAY="$(( 10#${BOOT_DELAY} ))"
+	if [ ${BOOT_DELAY} -gt 0 ] ; then
+		[ ${BOOT_DELAY} -gt ${MAX_BOOT_DELAY} ] && BOOT_DELAY=${MAX_BOOT_DELAY}
+		say "Applying a boot delay of ${BOOT_DELAY} seconds"
+		START="$(date +%s)"
+		while true ; do
+			DIFF="$(( $(date +%s) - START ))"
+			[ ${DIFF} -ge ${BOOT_DELAY} ] && break
+			sleep 1 || fail "Boot delay aborted - exiting"
+		done
+	fi
+fi
+
 set -- "${HOME_DIR}/bin/solr" start -f -cloud
 say "Launching Solr as: ${@@Q}"
 exec "${@}"
