Updated to the latest clustering stuff

diff --git a/src/solr/files/configmap/txt/entrypoint b/src/solr/files/configmap/txt/entrypoint
--- a/src/solr/files/configmap/txt/entrypoint
+++ b/src/solr/files/configmap/txt/entrypoint
@@ -35,35 +35,30 @@ fi
 [ -v SOLR_LOGS_DIR ] || export SOLR_LOGS_DIR="${DATA_DIR}/logs"
 [ -d "${SOLR_LOGS_DIR}" ] || mkdir -p "${SOLR_LOGS_DIR}" || say "WARNING: Failed to find and create the log directory at [${SOLR_LOGS_DIR}]"
 
-ZK_FLAGS=()
-if [ -v ZOOKEEPER ] ; then
+if [ -v ZK_HOST ] ; then
 	# Validate the hostnames
-	readarray -d , -t FLAGS < <(echo -n "${ZOOKEEPER}")
+	readarray -d , -t FLAGS < <(echo -n "${ZK_HOST}")
 	say "Validating the Zookeeper settings"
+	ZK=()
 	for H in "${FLAGS[@]}" ; do
 		# Each host must be in the form hostname:port
 		[ -n "${H}" ] || continue
-		[[ "${H}" =~ ^([^:]+):([1-9][0-9]*)$ ]] || fail "\tIgnoring the Zookeeper spec [${H}]: must be in the form \${hostname}:\${port}"
+		[[ "${H}" =~ ^([^:]+)(?::([1-9][0-9]*))?$ ]] || fail "\tIgnoring the Zookeeper spec [${H}]: must be in the form \${hostname}:\${port}"
 
 		HOST="${BASH_REMATCH[1]}"
-		[[ "${HOST}" =~ ^([a-z0-9][-a-z0-9]*)?[a-z0-9]([.]([a-z0-9][-a-z0-9]*)?[a-z0-9])*$ ]] || fail "\tIgnoring the Zookeeper spec [${H}]: invalid host name [${HOST}]"
+		[[ "${HOST}" =~ ^([a-z0-9][-a-z0-9]*)?[a-z0-9]([.]([a-z0-9][-a-z0-9]*)?[a-z0-9])*$ ]] || fail "\tInvalid Zookeeper spec [${H}]: invalid host name [${HOST}]"
 
-		PORT="${BASH_REMATCh[2]}"
-		[ ${PORT} -le 65535 ] || fail "\tIgnoring the Zookeeper spec [${H}]: invalid port number ${PORT}"
+		PORT="${BASH_REMATCh[3]}"
+		[ ${PORT} -le 65535 ] || fail "\tInvalid Zookeeper spec [${H}]: invalid port number ${PORT}"
 
 		say "\tAdding Zookeeper at ${HOST}:${PORT}"
-		ZK_FLAGS+=("${HOST}:${PORT}")
+		ZK+=("${HOST}:${PORT}")
 	done
 
-	if [ ${#ZK_FLAGS[@]} -gt 0 ] ; then
-		say "Found ${#ZK_FLAGS[@]} Zookeeper targets: ${ZK_FLAGS[@]}"
-		ZK_FLAGS=("-z" "${ZK_FLAGS[@]}")
-	else
-		say "No Zookeeper configurations, using the default"
-	fi
+	say "Setting the ZK_HOST value [${ZK_HOST}]"
+	export ZK_HOST="$(echo -n "${ZK[@]}" | tr ' ' ',')"
 fi
 
-
-set -- "${HOME_DIR}/bin/solr" start -f -cloud "${ZK_FLAGS[@]}"
+set -- "${HOME_DIR}/bin/solr" start -f -cloud
 say "Launching Solr as: ${@@Q}"
 exec "${@}"
