Many bugfixes, now works as intended

diff --git a/src/pvc-tool/clone-tools/convert-pvc-sc b/src/pvc-tool/clone-tools/convert-pvc-sc
--- a/src/pvc-tool/clone-tools/convert-pvc-sc
+++ b/src/pvc-tool/clone-tools/convert-pvc-sc
@@ -11,6 +11,9 @@ case "${DISABLE_CLONE,,}" in
 esac
 export DISABLE_CLONE
 
+[ -v RESULT_MARKER ] || RESULT_MARKER=""
+[ -n "${RESULT_MARKER}" ] || RESULT_MARKER="/.pod.result"
+
 POD_POLL_WAIT="10"
 POD_REBOOT_WAIT="60"
 POD_REBOOT_TIMEOUT="$(( POD_REBOOT_WAIT * 15 ))"
@@ -71,6 +74,49 @@ execute()
 	return ${?}
 }
 
+compute_pod_state()
+{
+	local JSON="${1}"
+	local STATE=""
+
+	# If the JSON is non-empty and valid then we can compute the real state
+	STATE="missing"
+	[ -n "${JSON}" ] && "${JQ}" -r <<< "${JSON}" &>/dev/null && STATE=""
+	[ -n "${STATE}" ] && echo -n "${STATE}" && return 0
+
+	# The pod exists ... is it terminating?
+	local DELETION_TS="$("${JQ}" -r ".metadata.deletionTimestamp // \"\"" <<< "${JSON}")"
+	[ -n "${DELETION_TS}" ] && STATE="terminating"
+	[ -n "${STATE}" ] && echo -n "${STATE}" && return 0
+
+	# It's not terminating ... maybe it's ready?
+	local COND=""
+
+	COND="$("${JQ}" -r '.status.conditions[] | select(.type == "Ready") | .status' <<< "${JSON}")"
+	[ "${COND,,}" == "true" ] && STATE="ready"
+	[ -n "${STATE}" ] && echo -n "${STATE}" && return 0
+
+	COND="$("${JQ}" -r '.status.conditions[] | select(.type == "Initialized") | .status' <<< "${JSON}")"
+	[ "${COND,,}" == "true" ] && STATE="started"
+	[ -n "${STATE}" ] && echo -n "${STATE}" && return 0
+
+	# If it's not missing, not ready, not started, and not terminating, it MUST be created
+	echo -n "created"
+	return 0
+}
+
+get_pod_state()
+{
+	local POD="${1}"
+
+	local JSON=""
+
+	# If this call fails, it's because the pod doesn't exist
+	JSON="$("${KUBECTL}" get pod --namespace "${NAMESPACE}" "${POD}" -o json 2>&1)" || JSON=""
+	compute_pod_state "${JSON}"
+	return 0
+}
+
 get_deployment_status()
 {
 	local STATUS=""
@@ -82,7 +128,7 @@ get_deployment_status()
 	# superseded, failed, uninstalling, pending-install,
 	# pending-upgrade or pending-rollback
 	local RESULT=""
-	RESULT="$("${JQ}" -r '.info.status' <<< "${STATUS}")" || return ${?}
+	RESULT="$("${JQ}" -r ".info.status" <<< "${STATUS}")" || return ${?}
 	echo -n "${RESULT}"
 	return 0
 }
@@ -142,171 +188,6 @@ deploy_chart()
 		--set mode=clone || fail "Unable to deploy the chart"
 }
 
-wait_until_pod_exists()
-{
-	local POD="${1}"
-	local NEXT_WAIT=${POD_REBOOT_WAIT}
-	local FIRST="true"
-	local START="$(/usr/bin/date +%s)"
-	local END="$(( START + POD_REBOOT_TIMEOUT ))"
-	while true; do
-		if ! "${FIRST}" ; then
-			# Apply the polling wait ...
-			say "💤 Sleeping for ${NEXT_WAIT} before checking for its existence again..."
-			/usr/bin/sleep ${NEXT_WAIT} || return ${?}
-		fi
-
-		"${KUBECTL}" get pod \
-			--namespace "${NAMESPACE}" "${POD}" &>/dev/null && \
-			is_pod_waitable "${POD}" && \
-			return 0
-
-		"${FIRST}" && warn "The pod ${NAMESPACE}/${POD} doesn't exist yet..."
-		FIRST="false"
-
-		local NOW="$(/usr/bin/date +%s)"
-		[ $(( NOW - START )) -ge ${POD_REBOOT_TIMEOUT} ] && break
-		[ $(( NOW + NEXT_WAIT )) -lt ${END} ] || NEXT_WAIT=$(( END - NOW ))
-	done
-
-	# Should never happen, but if it does...
-	err "The pod didn't come up in ${POD_REBOOT_TIMEOUT} seconds, can't wait anymore"
-	return 1
-}
-
-wait_until_pod_is_initialized()
-{
-	local POD="${1}"
-
-	local OUT=""
-
-	local RC=${?}
-	return ${RC}
-
-	local NEXT_WAIT=${POD_REBOOT_WAIT}
-	local FIRST="true"
-	local START="$(/usr/bin/date +%s)"
-	local END="$(( START + POD_REBOOT_TIMEOUT ))"
-	while true; do
-		"${FIRST}" || say "💤 Waiting for ${NEXT_WAIT} seconds before checking for its status again..."
-		OUT="$("${KUBECTL}" wait pod \
-			--namespace "${NAMESPACE}" "${POD}" \
-			--for condition=Initialized=true \
-			--timeout="${NEXT_WAIT}s" 2>&1)" && return 0
-
-		# Edge case: the pod is killed while we were waiting
-		is_pod_waitable "${POD}" || return ${?}
-
-		"${FIRST}" && warn "The pod ${NAMESPACE}/${POD} isn't initialized yet..."
-		FIRST="false"
-
-		local NOW="$(/usr/bin/date +%s)"
-		[ $(( NOW - START )) -ge ${POD_REBOOT_TIMEOUT} ] && break
-		[ $(( NOW + NEXT_WAIT )) -lt ${END} ] || NEXT_WAIT=$(( END - NOW ))
-	done
-
-	# Should never happen, but if it does...
-	err "Failed to wait for pod initialization (rc=${RC})\n${OUT}"
-	return 1
-}
-
-get_pod_status()
-{
-	local POD="${1}"
-	local CONTAINER="${2}"
-	local STATUS="${3}"
-
-	local OUT=""
-	local RC=0
-	OUT="$("${KUBECTL}" get pod --namespace "${NAMESPACE}" "${POD}" -o jsonpath="{.status.containerStatuses[?(@.name==\"${CONTAINER}\")].${STATUS}}" 2>&1)" || RC=${?}
-	if [ ${RC} -ne 0 ] || [ -z "${OUT}" ] ; then
-		err "Failed to query the pod's container ${STATUS} status (rc=${RC})\n${OUT}"
-		return ${RC}
-	fi
-
-	echo -n "${OUT}"
-	return 0
-}
-
-is_job_complete()
-{
-	local POD="${1}"
-
-	local STATUS=""
-	STATUS="$(get_pod_status "${POD}" "clone" "ready")" || return ${?}
-
-	# Status is expected to be either "true" or "false"
-	case "${STATUS}" in
-		true | false ) "${STATUS}" && return 0 ;;
-		* ) return 1 ;;
-	esac
-
-	return 1
-}
-
-wait_until_pod_is_running()
-{
-	local POD="${1}"
-	local NEXT_WAIT=${POD_REBOOT_WAIT}
-	local FIRST="true"
-	local START="$(/usr/bin/date +%s)"
-	local END="$(( START + POD_REBOOT_TIMEOUT ))"
-	while true; do
-		if ! "${FIRST}" ; then
-			# Apply the polling wait ...
-			say "💤 Sleeping for ${NEXT_WAIT} before checking for status again..."
-			/usr/bin/sleep ${NEXT_WAIT} || return ${?}
-		fi
-
-		wait_until_pod_is_initialized "${POD}" || return ${?}
-
-		local STATUS=""
-		STATUS="$(get_pod_status "${POD}" "clone" "started")" || STATUS="false"
-
-		# Status is expected to be either "true" or "false"
-		case "${STATUS}" in
-			true | false ) "${STATUS}" && return 0 ;;
-			* ) return 1 ;;
-		esac
-
-		"${FIRST}" && warn "The pod ${NAMESPACE}/${POD} isn't running yet..."
-		FIRST="false"
-
-		local NOW="$(/usr/bin/date +%s)"
-		[ $(( NOW - START )) -ge ${POD_REBOOT_TIMEOUT} ] && break
-		[ $(( NOW + NEXT_WAIT )) -lt ${END} ] || NEXT_WAIT=$(( END - NOW ))
-	done
-
-	# Should never happen, but if it does...
-	err "The pod didn't start running in ${POD_REBOOT_TIMEOUT} seconds, can't wait anymore"
-	return 1
-}
-
-wait_until_job_completes()
-{
-	local POD="${1}"
-
-	local NEXT_WAIT=${POD_POLL_WAIT}
-	local FIRST="true"
-	while true; do
-		"${FIRST}" || say "💤 Waiting for ${NEXT_WAIT} seconds before checking for its status again..."
-		OUT="$("${KUBECTL}" wait pod \
-			--namespace "${NAMESPACE}" "${POD}" \
-			--for condition=Ready=true \
-			--timeout="${NEXT_WAIT}s" 2>&1)" && return 0
-
-		# Edge case: the pod is killed while we were waiting
-		is_pod_waitable "${POD}" || return ${?}
-
-		"${FIRST}" && warn "The job at ${NAMESPACE}/${POD} isn't finished yet, maybe follow it with kubectl logs?"
-		FIRST="false"
-	done
-
-	# Should never happen, but if it does...
-	err "Failed to wait for the job to complete (rc=${RC})\n${OUT}"
-	return 1
-}
-
 track_logs()
 {
 	local POD="${1}"
@@ -318,61 +199,115 @@ track_logs()
 	return ${?}
 }
 
-get_pod_phase()
+wait_for_condition()
 {
 	local POD="${1}"
-
-	local OUT=""
-	OUT="$("${KUBECTL}" get pod --namespace "${NAMESPACE}" "${POD}" -o jsonpath='{ .status.phase }' 2>&1)"
-
-	local RC=${?}
-	[ ${RC} -eq 0 ] && echo -n "${OUT}"
-	return ${RC}
+	local CONDITION="${2}"
+	local WAIT_TIMEOUT="${3:-30s}"
+	# We will wait for the pod to be initialized
+	"${KUBECTL}" wait pod \
+		--namespace "${NAMESPACE}" "${POD}" \
+		--for "${CONDITION}" \
+		--timeout="${WAIT_TIMEOUT}" \
+		-o json 2>&1
 }
 
 get_copy_result()
 {
 	local POD="${RELEASE}-0"
 
-	say "👉 Wait for the file copy to conclude..."
-	local POD_STATUS=""
+	local OLD_STATE=""
+	local NEW_STATE=""
+	local FIRST="true"
+	local RC=0
+	local STATE_CHANGED="false"
+	local POLL_WAIT=""
+	local POLL_NEXT="true"
+	local JSON=""
+	local MISSING_PREFIX=""
 	while true; do
-		# Step 1: wait until the pod exists
-		wait_until_pod_exists "${POD}" || fail "The pod did not come online"
-
-		if ! is_job_complete "${POD}" ; then
-			# Step 2: wait until the pod is running
-			ok "The pod ${NAMESPACE}/${POD} exists! Waiting for it to be Ready"
-			wait_until_pod_is_running "${POD}" || fail "The pod never reached the running state"
-
-			# Step 3: Track the logs, so the user can see what's going on
-			ok "The pod ${NAMESPACE}/${POD} is running!"
-
-			# Tracking the logs no longer works b/c the pod will never exit...b/c we're
-			# using a statefulset so it will restart our pod for us in the event that
-			# it crashes on us. This way, the copy will continue automagically until
-			# it's either completed, or found to be irrevocably failed...
-			# say "👀 Tracking the logs for ${NAMESPACE}/${POD}"
-			# track_logs "${POD}"
-
-			# We have to wait until the pod enters the Ready state. If it dies on us,
-			# then we have to start all over again
-			if ! wait_until_job_completes "${POD}" ; then
-				err "The pod may have crashed, restarting the monitoring loop"
-				continue
+		if "${POLL_NEXT}" ; then
+			[[ "${POLL_WAIT}" =~ ^(0|[1-9][0-9]*)$ ]] || POLL_WAIT="${POD_POLL_WAIT}"
+			if ! "${FIRST}" && [ ${POLL_WAIT} -gt 0 ] ; then
+				say "💤 Sleeping for ${POLL_WAIT}..."
+				/usr/bin/sleep ${POLL_WAIT} || fail "Interrupted while sleeping"
 			fi
 
-			ok "The pod ${NAMESPACE}/${POD} appears to have completed its work"
-		else
-			ok "The pod ${NAMESPACE}/${POD} already completed its work"
+			OLD_STATE="${NEW_STATE}"
+			NEW_STATE="$(get_pod_state "${POD}")"
 		fi
+		FIRST="false"
 
-		# Step 4: Pod has exited (or somesuch)...get its termination status
-		local RESULT=""
-		RESULT="$("${KUBECTL}" exec --namespace "${NAMESPACE}" "${POD}" -- /usr/bin/cat /.pod.result 2>&1)" && return ${RESULT}
+		# We always re-set the poller
+		POLL_NEXT="true"
+		POLL_WAIT="${POD_POLL_WAIT}"
 
-		# Something's off ... pod exited, but we can't get the status ...
-		err "Failed to retrieve the pod status ... will try again (rc=${RC}):\n${RESULT}"
+		STATE_CHANGED="false"
+		[ "${OLD_STATE}" == "${NEW_STATE}" ] || STATE_CHANGED="true"
+
+		[ "${NEW_STATE}" != "missing" ] && MISSING_PREFIX="re"
+
+		CONDITION=""
+		case "${NEW_STATE}" in
+			terminating )
+				"${STATE_CHANGED}" && say "👉 The pod is terminating, waiting for it to disappear completely"
+				CONDITION="delete"
+				;;
+
+			missing )
+				# TODO: Enable the maximum wait timer so we don't wait forever for it to be created
+				"${STATE_CHANGED}" && say "👉 The pod is missing, waiting for it to ${MISSING_PREFIX}appear..."
+				"${KUBECTL}" get pod --namespace "${NAMESPACE}" "${POD}" &>/dev/null || continue
+				CONDITION="condition=PodScheduled"
+				;;
+
+			created )
+				# TODO: Enable the maximum wait timer so we don't wait forever for it to start running
+				"${STATE_CHANGED}" && say "👉 The pod seems to be scheduled, will wait for initialization to complete..."
+				CONDITION="condition=Initialized"
+				;;
+
+			started )
+				"${STATE_CHANGED}" && say "👉 The copy seems to be running, waiting for it to conclude..."
+				CONDITION="condition=Ready"
+				;;
+
+			ready )
+				if ! "${STATE_CHANGED}" ; then
+					# If the pod's state didn't change between last cycle and this one, then
+					# it's a terminating problem b/c the pod is ready, but didn't store its
+					# result in the expected location
+					err "The pod seems to have completed its work, but there's no result, please take a closer look at ${NAMESPACE}/${POD}."
+					return 1
+				fi
+
+				# The happy path - we just went from "whatever" into Ready, which
+				# means the copy has completed and we have a result to harvest...
+				ok "The pod appears to have completed its work"
+				local RESULT=""
+				RC=0
+				RESULT="$("${KUBECTL}" exec --namespace "${NAMESPACE}" "${POD}" -- /usr/bin/cat "${RESULT_MARKER}" 2>/dev/null)" || RC=${?}
+				[ ${RC} -eq 0 ] && return ${RESULT}
+
+				# If the RC isn't 0 it means there's something off and we weren't able
+				# to get the result, so we loop back up to poll again, and see what's up...
+				warn "Failed to retrieve the copy's result status marker (rc=${RC}), checking the pod state again"
+				POLL_WAIT="0"
+				continue
+				;;
+		esac
+
+		[ -n "${CONDITION}" ] || continue
+
+		POLL_WAIT=0
+		# If the wait failed, it must have timed out, so start from scratch, but no sleep
+		JSON="$(wait_for_condition "${POD}" "${CONDITION}")" || continue
+
+		# We have a possible new read on the pod, analyze it without
+		# causing a sleep
+		OLD_STATE="${NEW_STATE}"
+		NEW_STATE="$(compute_pod_state "${JSON}")"
+		POLL_NEXT="false"
 	done
 }
 
@@ -418,11 +353,11 @@ if ! is_namespace_exists "${NAMESPACE}" ; then
     exit 0
 fi
 
-deploy_chart || fail "Couldn't deploy the chart to do the volume cloning"
+# deploy_chart || fail "Couldn't deploy the chart to do the volume cloning"
 ok "Chart deployed!"
 
 get_copy_result || fail "The file copy seems to have failed, please review the full logs for more information"
 ok "Copy complete!"
 
-undeploy_chart || fail "Couldn't un-deploy the chart"
+# undeploy_chart || fail "Couldn't un-deploy the chart"
 ok "Undeployment completed!"
