Many pentaho script fixes. Init lock now works

diff --git a/src/pentaho/files/configmap/txt/entrypoint b/src/pentaho/files/configmap/txt/entrypoint
--- a/src/pentaho/files/configmap/txt/entrypoint
+++ b/src/pentaho/files/configmap/txt/entrypoint
@@ -179,10 +179,15 @@ INITIALIZER_PROCESS="/config-post.sh"
 MARKER="$(dd if=/dev/urandom bs=3 count=16 2>/dev/null | base64 --wrap=0)"
 say "Acquiring the initializer lock"
 coproc "/lock-initializer" "${MARKER}" "${INITIALIZER_PROCESS}"
-COPROC_OUT="${COPROC[0]}"
+LOCK_OUT="${COPROC[0]}"
+LOCK_PID="${COPROC_PID}"
+say "Co-process started (pid=${LOCK_PID}, fd=${LOCK_OUT})"
+
+RC=0
+LAUNCH="exec"
 while true ; do
 	# Has the marker been output?
-	if read -u ${COPROC_OUT} LINE ; then
+	if read -u ${LOCK_OUT} LINE &>/dev/null ; then
 		# A successful read ...
 
 		# If it's not our marker, keep reading!
@@ -190,18 +195,22 @@ while true ; do
 
 		# If it was our marker, end the loop!
 		say "Initialization lock acquired"
+		# Don't use exec to launch Pentaho
+		LAUNCH=""
 		break
 	fi
 
 	# The read failed ... is the coproc still running?
-	kill -0 ${COPROC_PID} &>/dev/null && continue
+	kill -0 ${LOCK_PID} &>/dev/null && continue
 
 	# It's not running... did it exit successfully?
-	wait ${COPROC_PID} || RC=${?}
-	[ ${RC} -eq 0 ] && break
+	wait ${LOCK_PID} &>/dev/null || RC=${?}
 
 	# If it's not running and its exit status is not 0, then there was
-	fail "Initializer lock failed - cannot continue (rc=${RC})"
+	[ ${RC} -eq 0 ] || fail "Initializer lock failed - cannot continue (rc=${RC})"
+
+	say "Another process executed the initialization"
+	break
 done
 
 ###################################################################
@@ -209,5 +218,6 @@ done
 ###################################################################
 
 CMD=("${PENTAHO_SERVER}/start-pentaho.sh" "${@}")
+[ -z "${LAUNCH}" ] || CMD=("${LAUNCH}" "${CMD[@]}")
 say "Launching Pentaho as: ${CMD[@]@Q}"
-exec "${CMD}"
+"${CMD}"
