Added a bootup wait to Pentaho, updated image
Pentaho in a cluster is not a very happy boy, so I added a bootup delay in hopes of helping bring joy to its world.

diff --git a/src/pentaho/files/configmap/txt/entrypoint b/src/pentaho/files/configmap/txt/entrypoint
--- a/src/pentaho/files/configmap/txt/entrypoint
+++ b/src/pentaho/files/configmap/txt/entrypoint
@@ -231,6 +231,20 @@ if [ -n "${LAUNCH}" ] ; then
 		[[ "${BOOT_DELAY}" =~ ^[1-9][0-9]*$ ]] || BOOT_DELAY="30"
 		say "Applying a delay of ${BOOT_DELAY} seconds (don't ask... thank Hitachi)"
 		sleep "${BOOT_DELAY}" || fail "Initial delay interrupted, can't continue"
+	else
+		# We didn't have to wait for the lock. However, Pentaho is still
+		# bitchy about true concurrent booting against the same databases
+		# (thanks, Hitachi!). Thus, we must apply a (variable) delay...
+		#
+		# Get the pod ID, multiply it by 10, and apply it as a boot delay.
+		BOOT_DELAY=0
+		MUL=0
+		[[ "${POD_NAME}" =~ -([0-9]*)$ ]] && MUL="${BASH_REMATCH[1]}"
+		[ ${MUL} -gt 0 ] && BOOT_DELAY=$(( MUL * 30 ))
+		if [ ${BOOT_DELAY} -gt 0 ] ; then
+			say "Applying a safety delay of ${BOOT_DELAY} seconds (again... thank Hitachi)"
+			sleep "${BOOT_DELAY}" || fail "Safety delay interrupted, can't continue"
+		fi
 	fi
 fi
 say "Launching Pentaho as: ${CMD[@]@Q}"
