Minor tweaks to the deploy script

diff --git a/src/core/files/configmap/txt/deploy b/src/core/files/configmap/txt/deploy
--- a/src/core/files/configmap/txt/deploy
+++ b/src/core/files/configmap/txt/deploy
@@ -5,7 +5,6 @@ set -euo pipefail
 [ -v DEPL_DIR ] || DEPL_DIR="${BASE_DIR}/depl"
 [ -v CONF_DIR ] || CONF_DIR="${DEPL_DIR}/conf"
 [ -v WARS_DIR ] || WARS_DIR="${DEPL_DIR}/wars"
-[ -v FORCE_DEPLOY ] || FORCE_DEPLOY="false"
 
 # Temporarily put them here... eventually they'll have
 # a dedicated place to live
@@ -22,10 +21,17 @@ fail() {
 
 [ -v SKIP_WARS ] || SKIP_WARS=""
 [ -v SKIP_CONF ] || SKIP_CONF="false"
+
 [ -v DEV ] || DEV="false"
 case "${DEV,,}" in
 	true | t | yes | y | on | en | enabled | enable | 1 ) DEV="true" ;;
 	* ) DEV="false" ;;
+esac
+
+[ -v FORCE_DEPLOY ] || FORCE_DEPLOY="false"
+case "${FORCE_DEPLOY,,}" in
+	true | t | yes | y | on | en | enabled | enable | 1 ) FORCE_DEPLOY="true" ;;
+	* ) FORCE_DEPLOY="false" ;;
 esac
 
 if ${DEV} ; then
@@ -114,13 +120,12 @@ if ! ${SKIP_CONF} ; then
 	say "Found ${#EXTS[@]} EXTS files to deploy: [${EXTS[@]}]"
 
 	# Make sure the extensions are deployed ALWAYS
-	export OLD_FORCE_DEPLOY="${FORCE_DEPLOY}"
-	export FORCE_DEPLOY="true"
-	for ext in "${EXTS[@]}" ; do
-		deploy-artifact extract "${ext}" "${EXTS_DIR}" || fail "Failed to deploy the extension from [${ext}]"
-	done
-	export FORCE_DEPLOY="${OLD_FORCE_DEPLOY}"
-	unset OLD_FORCE_DEPLOY
+	(
+		export FORCE_DEPLOY="true"
+		for ext in "${EXTS[@]}" ; do
+			deploy-artifact extract "${ext}" "${EXTS_DIR}" || fail "Failed to deploy the extension from [${ext}]"
+		done
+	) || exit ${?}
 fi
 
 #
