Handle deployments more rigorously

diff --git a/src/core/files/configmap/txt/deploy b/src/core/files/configmap/txt/deploy
--- a/src/core/files/configmap/txt/deploy
+++ b/src/core/files/configmap/txt/deploy
@@ -38,8 +38,11 @@ fi
 #
 # Deploy all WAR files
 #
-while read war ; do
-	
+WAR="$(list-artifacts /arkcase/wars)" || fail "Failed to list the WAR files to be deployed"
+readarray -t WAR <<< "${WAR}"
+say "Found ${#WAR[@]} WAR files to deploy: [${WAR[@]}]"
+for war in "${WAR[@]}" ; do
+
 	if ${DEV} ; then
 		ARTIFACT_NAME="${war##*/}"
 		BASENAME="${ARTIFACT_NAME%.*}"
@@ -65,8 +68,8 @@ while read war ; do
 
 	# There's no development version, and the WAR is not excluded,
 	# so let's go ahead and deploy it normally
-	deploy-artifact extractdir "${war}" "${WARS_DIR}"
-done < <(list-artifacts /arkcase/wars)
+	deploy-artifact extractdir "${war}" "${WARS_DIR}" || fail "Failed to deploy the WAR from [${war}]"
+done
 
 if ${DEV} ; then
 	ARTIFACT_NAME="01-conf.zip"
@@ -84,15 +87,18 @@ if ! ${SKIP_CONF} ; then
 	#
 	# Deploy all the .arkcase configurations
 	#
-	while read conf ; do
-		deploy-artifact extract "${conf}" "${CONF_DIR}"
-	done < <(list-artifacts /arkcase/conf)
+	CONF="$(list-artifacts /arkcase/conf)" || fail "Failed to list the CONF files to be deployed"
+	readarray -t CONF <<< "${CONF[@]}"
+	say "Found ${#CONF[@]} CONF files to deploy: [${CONF[@]}]"
+	for conf in "${CONF[@]}" ; do
+		deploy-artifact extract "${conf}" "${CONF_DIR}" || fail "Failed to deploy the configuration from [${conf}]"
+	done
 fi
 
 #
 # This is the only fix we know must be applied FOR SURE each time
 #
-realm-fix
+realm-fix || fail "Failed to fix the realms information in the rules files"
 
 say "Configuration Initialization Complete"
 exit 0
diff --git a/src/pentaho/files/configmap/txt/deploy b/src/pentaho/files/configmap/txt/deploy
--- a/src/pentaho/files/configmap/txt/deploy
+++ b/src/pentaho/files/configmap/txt/deploy
@@ -19,20 +19,24 @@ fail() {
 #
 # Deploy all reports
 #
-say "Deploying any base reports for automated installation"
+REPORT="$(list-artifacts /pentaho/reports)" || fail "Failed to list the reports for deployment"
+readarray -t REPORT <<< "${REPORT}"
+say "Deploying ${#REPORT[@]} reports for automated installation: [${REPORT[@]}]"
 mkdir -p "${REPS_DIR}"
-while read report ; do
+for report in "${REPORT[@]}" ; do
 	deploy-artifact copy "${report}" "${REPS_DIR}"
-done < <(list-artifacts /pentaho/reports)
+done
 
 #
 # Extract all the Data Warehousing stuff
 #
-say "Deploying Analytical Transformations"
+DWHS="$(list-artifacts /pentaho/analytical)" || fail "Failed to list the analytical transformations for deployment"
+readarray -t DWHS <<< "${REPORT}"
+say "Deploying ${#DWHS[@]} Analytical Transformations: [${DWHS[@]}]"
 mkdir -p "${DWHS_DIR}"
-while read dwhs ; do
+for dwhs in "${DWHS[@]}" ; do
 	deploy-artifact extract-dir "${dwhs}" "${DWHS_DIR}"
-done < <(list-artifacts /pentaho/analytical)
+done
 
 say "Artifact deployment complete"
 exit 0
